version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "019427"
      POSTGRES_DB: "fine_erp"
    ports:
      - "5436:5432"
    volumes:
      - compress_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8001:8001"
    environment:
      NODE_ENV: production
      FINE_ENGINEERING_PORT: 8001

      # --- Add your application secrets here ---
      JWT_SECRET: ""

      # Writer DB config
      PGHOST_WRITER: db
      PGPORT_WRITER: 5432
      PGUSER_WRITER: postgres
      PGPASSWORD_WRITER: "019427"
      PGDATABASE_WRITER: fine_erp

      # Reader DB config
      PGHOST_READER: db
      PGPORT_READER: 5432
      PGUSER_READER: postgres
      PGPASSWORD_READER: "019427"
      PGDATABASE_READER: fine_erp

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./config:/usr/src/app/config

volumes:
  compress_pgdata: