import { DataTypes, Model, Optional, Sequelize } from "sequelize";

export interface AmcEstimateItemAttrs {
    id: string;
    estimate_id: string;

    ac_type: string;
    maker?: string | null;
    quantity: number;
    tr_per_ac?: number | null;
    rate_per_ac: number;

    line_total?: number | null; // generated by DB
    created_at?: Date;
    updated_at?: Date;
}
type AmcEstimateItemCreation = Optional<
    AmcEstimateItemAttrs,
    "id" | "maker" | "tr_per_ac" | "line_total" | "created_at" | "updated_at"
>;

export class AmcEstimateItem
    extends Model<AmcEstimateItemAttrs, AmcEstimateItemCreation>
    implements AmcEstimateItemAttrs {
    public id!: string;
    public estimate_id!: string;
    public ac_type!: string;
    public maker!: string | null;
    public quantity!: number;
    public tr_per_ac!: number | null;
    public rate_per_ac!: number;
    public line_total!: number | null;
    public created_at!: Date;
    public updated_at!: Date;
}

export const initAmcEstimateItemModel = (sequelize: Sequelize) => {
    AmcEstimateItem.init(
        {
            id: { type: DataTypes.UUID, primaryKey: true, defaultValue: DataTypes.UUIDV4 },
            estimate_id: { type: DataTypes.UUID, allowNull: false },

            ac_type: { type: DataTypes.TEXT, allowNull: false },
            maker: { type: DataTypes.TEXT },
            quantity: { type: DataTypes.INTEGER, allowNull: false },
            tr_per_ac: { type: DataTypes.DECIMAL(6, 2) },
            rate_per_ac: { type: DataTypes.DECIMAL(12, 2), allowNull: false },

            line_total: { type: DataTypes.DECIMAL(14, 2) }, // returned from DB generated column
            created_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
            updated_at: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
        },
        {
            sequelize,
            modelName: "AmcEstimateItem",
            tableName: "amc_estimate_items",
            timestamps: false,
            underscored: false,
        }
    );
    return AmcEstimateItem;
};
