// src/models/OrderBill.ts
import { Sequelize, DataTypes, Model, UUIDV4 } from "sequelize";

export class OrderBill extends Model {
    declare id: string;
    declare po_id: string;
    declare vendor_id: string;
    declare bill_number: string | null; // generated by DB trigger
    declare bill_date: Date;
    declare total_before_tax: number;
    declare total_tax: number;
    declare total_amount: number;
    declare payment_status: "pending" | "paid" | "partial" | string;
    declare notes: string | null;
    declare created_by: string | null;
    declare updated_by: string | null;
    declare created_at: Date;
    declare updated_at: Date;
    declare is_payment: boolean;
    static associate: (models: any) => void;
}

export const initOrderBillModel = (sequelize: Sequelize) => {
    OrderBill.init(
        {
            id: { type: DataTypes.UUID, defaultValue: UUIDV4, allowNull: false, primaryKey: true },
            po_id: { type: DataTypes.UUID, allowNull: false, references: { model: "purchase_orders", key: "id" } },
            vendor_id: { type: DataTypes.UUID, allowNull: false, references: { model: "vendors", key: "id" } },
            bill_number: { type: DataTypes.TEXT, allowNull: true, unique: true }, // DB trigger fills
            bill_date: { type: DataTypes.DATEONLY, allowNull: false },
            total_before_tax: { type: DataTypes.DECIMAL(14, 2), allowNull: false },
            total_tax: { type: DataTypes.DECIMAL(14, 2), allowNull: false, defaultValue: 0 },
            total_amount: { type: DataTypes.DECIMAL(14, 2), allowNull: false },
            payment_status: { type: DataTypes.TEXT, allowNull: false, defaultValue: "pending" },
            notes: { type: DataTypes.TEXT, allowNull: true },
            created_by: { type: DataTypes.UUID, allowNull: true },
            updated_by: { type: DataTypes.UUID, allowNull: true },
            created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
            updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
            // inside OrderBill.init({...})
            is_payment: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },

        },
        {
            sequelize,
            modelName: "OrderBill",
            tableName: "order_bills",
            timestamps: true,
            createdAt: "created_at",
            updatedAt: "updated_at",
            underscored: true,
            schema: "public",
        }
    );
    OrderBill.associate = function (models) {
        OrderBill.belongsTo(models.PurchaseOrder, {
            foreignKey: 'po_id',
            as: 'purchaseOrder'
        });
    };
    return OrderBill;
};
